Homework 1

In [20]:
import numpy as np

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [21]:
natural_numbers_vector = np.arange(1, 11)
print(natural_numbers_vector)

[ 1  2  3  4  5  6  7  8  9 10]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [22]:
zero_matrix = np.zeros((3, 3))
print(zero_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [23]:
random_matrix = np.random.randint(1, 11, size=(5, 5))
print(random_matrix)

[[ 7  2  5  6  9]
 [ 8  6 10 10  8]
 [10  5 10  4 10]
 [ 6  8  4  4 10]
 [10  6  6  3  2]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [24]:
matrix = np.random.rand(4, 4)
print(matrix)

[[0.51291165 0.20418887 0.48095695 0.80343028]
 [0.69517957 0.17871181 0.77999471 0.58520184]
 [0.86943956 0.8016991  0.67396202 0.5070811 ]
 [0.03506507 0.52804649 0.12384322 0.16800903]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [25]:
vector1 = np.random.randint(1, 11, size=5)
vector2 = np.random.randint(1, 11, size=5)

add_result = vector1 + vector2
sub_result = vector1 - vector2
mul_result = vector1 * vector2

print("Вектор 1:", vector1)
print("Вектор 2:", vector2)
print("Результат додавання:", add_result)
print("Результат віднімання:", sub_result)
print("Результат множення:", mul_result)

Вектор 1: [ 3 10  3  1  8]
Вектор 2: [4 3 1 1 4]
Результат додавання: [ 7 13  4  2 12]
Результат віднімання: [-1  7  2  0  4]
Результат множення: [12 30  3  1 32]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [26]:
vector1 = np.random.rand(7)
vector2 = np.random.rand(7)
dot_product = np.dot(vector1, vector2)

print("Вектор 1:", vector1)
print("Вектор 2:", vector2)
print("Скалярний добуток:", dot_product)

Вектор 1: [0.41918141 0.78817507 0.48177244 0.05827395 0.70873494 0.29622405
 0.84549169]
Вектор 2: [0.2040247  0.31632887 0.2391846  0.90760706 0.24362719 0.75531862
 0.69310424]
Скалярний добуток: 1.4853928054873662


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [27]:
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 3))

result = np.dot(matrix1, matrix2)

print(f"Перша матриця:\n{matrix1}")
print(f"Друга матриця:\n{matrix2}")
print(f"Результат множення матриць:\n{result}")

Перша матриця:
[[10  8]
 [ 5  1]]
Друга матриця:
[[ 2 10  9]
 [10 10  5]]
Результат множення матриць:
[[100 180 130]
 [ 20  60  50]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [28]:
matrix = np.random.randint(1, 11, size=(3, 3))
inverse_matrix = np.linalg.inv(matrix)

print(f"Матриця:\n{matrix}")
print(f"Обернена матриця:\n{inverse_matrix}")

Матриця:
[[ 3  2  8]
 [ 6  8  3]
 [ 1  4 10]]
Обернена матриця:
[[ 0.31192661  0.05504587 -0.26605505]
 [-0.26146789  0.10091743  0.17889908]
 [ 0.0733945  -0.04587156  0.05504587]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [29]:
matrix = np.random.rand(4, 4)
transposed_matrix = np.transpose(matrix)

print(f"Початкова матриця:\n{matrix}")
print(f"Транспонована матриця:\n{transposed_matrix}")

Початкова матриця:
[[0.93387076 0.53546467 0.57334718 0.04739875]
 [0.41599215 0.60604814 0.06135962 0.44735597]
 [0.3602538  0.51395139 0.48207495 0.74162905]
 [0.20631863 0.98149059 0.27362625 0.71028744]]
Транспонована матриця:
[[0.93387076 0.41599215 0.3602538  0.20631863]
 [0.53546467 0.60604814 0.51395139 0.98149059]
 [0.57334718 0.06135962 0.48207495 0.27362625]
 [0.04739875 0.44735597 0.74162905 0.71028744]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [30]:
matrix = np.random.randint(1, 11, size=(3, 4))
vector = np.random.randint(1, 11, size=4)
result = np.dot(matrix, vector)

print(f"Матриця 3x4:\n{matrix}")
print(f"Вектор 4:\n{vector}")
print(f"Результат множення:\n{result}")

Матриця 3x4:
[[ 3  6  9  5]
 [ 6  7  7  3]
 [ 7 10  8  9]]
Вектор 4:
[ 9 10  4  5]
Результат множення:
[148 167 240]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [31]:
matrix = np.random.rand(2, 3)
vector = np.random.rand(3)
result = np.dot(matrix, vector)

print(f"Матриця 2x3:\n{matrix}")
print(f"Вектор 3:\n{vector}")
print(f"Результат множення:\n{result}")

Матриця 2x3:
[[0.57459206 0.91765908 0.91049725]
 [0.59955919 0.24793159 0.16868025]]
Вектор 3:
[0.4965329  0.38122659 0.73074808]
Результат множення:
[1.30048401 0.51548175]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [32]:
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))
result = matrix1 * matrix2

print(f"Перша матриця 2x2:\n{matrix1}")
print(f"Друга матриця 2x2:\n{matrix2}")
print(f"Результат поелементного множення:\n{result}")

Перша матриця 2x2:
[[1 7]
 [9 3]]
Друга матриця 2x2:
[[7 5]
 [1 2]]
Результат поелементного множення:
[[ 7 35]
 [ 9  6]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [33]:
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))
result = np.dot(matrix1, matrix2)

print(f"Перша матриця 2x2:\n{matrix1}")
print(f"Друга матриця 2x2:\n{matrix2}")
print(f"Результат добутку матриць:\n{result}")

Перша матриця 2x2:
[[3 5]
 [7 7]]
Друга матриця 2x2:
[[4 8]
 [4 4]]
Результат добутку матриць:
[[32 44]
 [56 84]]


14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [34]:
matrix = np.random.randint(1, 101, size=(5, 5))
sum_of_elements = np.sum(matrix)

print(f"Матриця 5x5:\n{matrix}")
print(f"Сума елементів матриці: {sum_of_elements}")

Матриця 5x5:
[[94 94 48 27 36]
 [21 58  3 97 74]
 [51 80 53 62 46]
 [10 26 83 91  9]
 [61 80 57 55 55]]
Сума елементів матриці: 1371


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [35]:
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))
difference = matrix1 - matrix2

print(f"Перша матриця 4x4:\n{matrix1}")
print(f"Друга матриця 4x4:\n{matrix2}")
print(f"Різниця матриць:\n{difference}")

Перша матриця 4x4:
[[ 2  6  4  2]
 [ 4  5  7  4]
 [ 7  7  6  4]
 [ 6 10 10  2]]
Друга матриця 4x4:
[[2 5 3 2]
 [1 1 6 3]
 [6 9 5 9]
 [3 6 5 3]]
Різниця матриць:
[[ 0  1  1  0]
 [ 3  4  1  1]
 [ 1 -2  1 -5]
 [ 3  4  5 -1]]


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [36]:
matrix = np.random.rand(3, 3)
row_sums = np.sum(matrix, axis=1)
sum_vector = row_sums.reshape(-1, 1)

print(f"Матриця 3x3:\n{matrix}")
print(f"Вектор-стовпчик із сумами рядків:\n{sum_vector}")

Матриця 3x3:
[[0.19387437 0.13302838 0.86970028]
 [0.20969717 0.02317213 0.28276705]
 [0.03798931 0.64712595 0.90269806]]
Вектор-стовпчик із сумами рядків:
[[1.19660303]
 [0.51563634]
 [1.58781331]]


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [37]:
matrix = np.random.randint(-100, 100, size=(3, 4))
squared_matrix = matrix ** 2

print(f"Початкова матриця 3x4:\n{matrix}")
print(f"Матриця з квадратами чисел:\n{squared_matrix}")

Початкова матриця 3x4:
[[ 45  71  15 -91]
 [-36 -80 -90 -56]
 [ -6  38 -23   4]]
Матриця з квадратами чисел:
[[2025 5041  225 8281]
 [1296 6400 8100 3136]
 [  36 1444  529   16]]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [38]:
vector = np.random.randint(1, 51, size=4)
sqrt_vector = np.sqrt(vector)

print(f"Початковий вектор розміром 4:\n{vector}")
print(f"Вектор з квадратними коренями:\n{sqrt_vector}")

Початковий вектор розміром 4:
[18 41 33 10]
Вектор з квадратними коренями:
[4.24264069 6.40312424 5.74456265 3.16227766]
