In [ ]:
import numpy as np

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [ ]:
natural_numbers_vector = np.arange(1, 11)
print(natural_numbers_vector)

2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [ ]:
zero_matrix = np.zeros((3, 3))
print(zero_matrix)

3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [ ]:
random_matrix = np.random.randint(1, 11, size=(5, 5))
print(random_matrix)

4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [ ]:
matrix = np.random.rand(4, 4)
print(matrix)

5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [ ]:
vector1 = np.random.randint(1, 11, size=5)
vector2 = np.random.randint(1, 11, size=5)

add_result = vector1 + vector2
sub_result = vector1 - vector2
mul_result = vector1 * vector2

print("Вектор 1:", vector1)
print("Вектор 2:", vector2)
print("Результат додавання:", add_result)
print("Результат віднімання:", sub_result)
print("Результат множення:", mul_result)

6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [ ]:
vector1 = np.random.rand(7)
vector2 = np.random.rand(7)
dot_product = np.dot(vector1, vector2)

print("Вектор 1:", vector1)
print("Вектор 2:", vector2)
print("Скалярний добуток:", dot_product)

7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [ ]:
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 3))

result = np.dot(matrix1, matrix2)

print(f"Перша матриця:\n{matrix1}")
print(f"Друга матриця:\n{matrix2}")
print(f"Результат множення матриць:\n{result}")

8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [ ]:
matrix = np.random.randint(1, 11, size=(3, 3))
inverse_matrix = np.linalg.inv(matrix)

print(f"Матриця:\n{matrix}")
print(f"Обернена матриця:\n{inverse_matrix}")

9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [ ]:
matrix = np.random.rand(4, 4)
transposed_matrix = np.transpose(matrix)

print(f"Початкова матриця:\n{matrix}")
print(f"Транспонована матриця:\n{transposed_matrix}")

10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [ ]:
matrix = np.random.randint(1, 11, size=(3, 4))
vector = np.random.randint(1, 11, size=4)
result = np.dot(matrix, vector)

print(f"Матриця 3x4:\n{matrix}")
print(f"Вектор 4:\n{vector}")
print(f"Результат множення:\n{result}")

11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [ ]:
matrix = np.random.rand(2, 3)
vector = np.random.rand(3)
result = np.dot(matrix, vector)

print(f"Матриця 2x3:\n{matrix}")
print(f"Вектор 3:\n{vector}")
print(f"Результат множення:\n{result}")

12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [ ]:
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))
result = matrix1 * matrix2

print(f"Перша матриця 2x2:\n{matrix1}")
print(f"Друга матриця 2x2:\n{matrix2}")
print(f"Результат поелементного множення:\n{result}")

13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [ ]:
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))
result = np.dot(matrix1, matrix2)

print(f"Перша матриця 2x2:\n{matrix1}")
print(f"Друга матриця 2x2:\n{matrix2}")
print(f"Результат добутку матриць:\n{result}")

14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [ ]:
matrix = np.random.randint(1, 101, size=(5, 5))
sum_of_elements = np.sum(matrix)

print(f"Матриця 5x5:\n{matrix}")
print(f"Сума елементів матриці: {sum_of_elements}")

15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [ ]:
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))
difference = matrix1 - matrix2

print(f"Перша матриця 4x4:\n{matrix1}")
print(f"Друга матриця 4x4:\n{matrix2}")
print(f"Різниця матриць:\n{difference}")

16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [20]:
matrix = np.random.rand(3, 3)
row_sums = np.sum(matrix, axis=1)
sum_vector = row_sums.reshape(-1, 1)

print(f"Матриця 3x3:\n{matrix}")
print(f"Вектор-стовпчик із сумами рядків:\n{sum_vector}")

Матриця 3x3:
[[0.86147951 0.72134098 0.96911195]
 [0.09317163 0.50129666 0.55804794]
 [0.57669505 0.51234038 0.50155641]]
Вектор-стовпчик із сумами рядків:
[[2.55193244]
 [1.15251623]
 [1.59059183]]


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [ ]:
matrix = np.random.randint(-100, 100, size=(3, 4))
squared_matrix = matrix ** 2

print(f"Початкова матриця 3x4:\n{matrix}")
print(f"Матриця з квадратами чисел:\n{squared_matrix}")

18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [ ]:
vector = np.random.randint(1, 51, size=4)
sqrt_vector = np.sqrt(vector)

print(f"Початковий вектор розміром 4:\n{vector}")
print(f"Вектор з квадратними коренями:\n{sqrt_vector}")